apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-more-transfer
  labels:
    app: bank-more-transfer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-more-transfer
  template:
    metadata:
      labels:
        app: bank-more-transfer
    spec:
      containers:
        - name: api
          image: bankmore/transfer:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: bank-more-transfer-config
            - secretRef:
                name: bank-more-transfer-secret
          livenessProbe:
            httpGet:
              path: /swagger/index.html
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /swagger/index.html
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
