apiVersion: v1
kind: Service
metadata:
  name: oracle
  namespace: bankmore
  labels:
    app: oracle
spec:
  ports:
    - port: 1521
      targetPort: 1521
      name: oracle
  selector:
    app: oracle
