apiVersion: v1
kind: Secret
metadata:
  name: bankmore-secrets
  namespace: bankmore
type: Opaque
stringData:
  oracle-password: "bankmore"
  oracle-app-password: "bankmore"
  oracle-connection: "User Id=bankmore;Password=bankmore;Data Source=oracle:1521/XEPDB1"
  jwt-secret: "BankMore-SuperSecretKey-AtLeast32CharactersLong!"
  internal-api-key: "BankMore-Internal-ApiKey-ForTransferService"
