apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-more-transfer
  namespace: bankmore
  labels:
    app: bank-more-transfer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-more-transfer
  template:
    metadata:
      labels:
        app: bank-more-transfer
    spec:
      containers:
        - name: transfer
          image: bankmore/transfer:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: bankmore-secrets
                  key: oracle-connection
            - name: Jwt__Secret
              valueFrom:
                secretKeyRef:
                  name: bankmore-secrets
                  key: jwt-secret
            - name: Jwt__Issuer
              value: "BankMore.CurrentAccount"
            - name: Jwt__Audience
              value: "BankMore"
            - name: CurrentAccountApi__BaseUrl
              value: "http://bank-more-current-account:8080"
            - name: CurrentAccountApi__InternalApiKey
              valueFrom:
                secretKeyRef:
                  name: bankmore-secrets
                  key: internal-api-key
            - name: Kafka__BootstrapServers
              valueFrom:
                configMapKeyRef:
                  name: bankmore-config
                  key: kafka-bootstrap
            - name: Kafka__TopicTransfersCompleted
              valueFrom:
                configMapKeyRef:
                  name: bankmore-config
                  key: kafka-topic-transfers
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bank-more-transfer
  namespace: bankmore
spec:
  selector:
    app: bank-more-transfer
  ports:
    - port: 8080
      targetPort: 8080
      name: http
