# Replace placeholder values and encode with: kubectl create secret generic ... --dry-run=client -o yaml
apiVersion: v1
kind: Secret
metadata:
  name: bank-more-current-account-secret
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "User Id=bankmore;Password=bankmore;Data Source=oracle-service:1521/XEPDB1"
  Jwt__Secret: "BankMore-SuperSecretKey-AtLeast32CharactersLong!"
